language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
before_install:
  - wget https://github.com/jgm/pandoc/releases/download/2.2.1/pandoc-2.2.1-1-amd64.deb
  - sudo dpkg -i pandoc-2.2.1-1-amd64.deb
  - pandoc -v
install:
  - pip install coveralls
script:
  - coverage run --source=pandoc_latex_admonition setup.py test
after_success:
  - coveralls
