language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
before_install:
  - wget https://github.com/jgm/pandoc/releases/download/2.2.3.2/pandoc-2.2.3.2-1-amd64.deb
  - sudo dpkg -i pandoc-2.2.3.2-1-amd64.deb
  - pandoc -v
install:
  - pip install coveralls
  - pip install tox-travis
script:
  - tox
  - coverage run --source=pandoc_latex_admonition setup.py test
  - coverage report -m
after_success:
  - coveralls
